version: '3.7'

services:
  my-api:
    image: my-api:latest
    build: 
      dockerfile: Dockerfile
    command: ["/bin/svc"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 8081:8081
  minio-server:
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server  --console-address ":37717" ./data
    ports:
      - 9000:9000
      - 37717:37717
    volumes:
      - data1-1:/data1

volumes:
  data1-1:
